use PracticS4;
go

SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRAN
	SELECT * FROM Facturi;
	WAITFOR DELAY '00:00:15'
	SELECT * FROM Facturi;
COMMIT TRAN