USE Problema1;
go

SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRAN
	SELECT * FROM Briose;
	WAITFOR DELAY '00:00:15'
	SELECT * FROM Briose;
COMMIT TRAN

select * from Briose;