USE SCOALASGBD;
GO
--PHANTOM READS - T2: select + delay + select
-- PROBLEM: SET TRANSACTION ISOLATION LEVEL REPEATABLE READ/ - SOLUTION: SERIALIZABLE

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE --PROBLEM: LEVEL REPEATABLE READ
BEGIN TRAN
	SELECT * FROM Elevi;
	INSERT INTO LogTable(operationType, tableName, executionTime) VALUES ('SELECT', 'Elevi', CURRENT_TIMESTAMP)
	WAITFOR DELAY '00:00:07'
	SELECT * FROM Elevi;
	INSERT INTO LogTable(operationType, tableName, executionTime) VALUES ('SELECT', 'Elevi', CURRENT_TIMESTAMP)
COMMIT TRAN
